### PR TITLE
Migrate from native dependencies to nuget packages

### PR DESCRIPTION
**Pull request by Romfos**
Changes in this PR:
- All native dependencies were replaced to nuget packages
- Some mangosvb tools were fixed and now are building successfully
- Readme was updated
- Some unusable code\files were removed
- Migrate VB tools to .NET Core
- Refactroing project structure
- Added x64 patform support

---
This change is [Reviewable](https://reviewable.io/reviews/mangosvb/serverzero/132)

### CODE REVIEW

**Review by billy1arm — CHANGES_REQUESTED** [review]
Is it possible to target MySql 4.7 rather than 8.0
- There are some issues with 8.0 which will need fixing before we can use it safely.

**Comment by Romfos** [comment]
@billy1arm 

In project readme we have label 'MySQL Community Server 5.6 or later'
I've tested this changes on 5.6 and it works. 

Unfortunately i don't know about 4.7 version. Do we need support so old versions in 2020?

**Comment by billy1arm** [comment]
> @billy1arm
> 
> In project readme we have label 'MySQL Community Server 5.6 or later'
> I'm using 5.6 for my for local db and it works.
> Unfortunately i don't know about 4.7 version. Do we need support so old versions in 2020?

My apologies.... 5.7

**Comment by Romfos** [comment]
@billy1arm I don't see any trouble with 5.7. 
Could you please tell me what is wrong with 5.7?

**Comment by billy1arm** [comment]
5.7 is fine, 8.0 has issues - sorry for the confusion

**Comment by Romfos** [comment]
@billy1arm I'm not able to apply migrations for 8.0, because tool 'mysql.exe' in DatabaseZero repo is outdated for 8.0

`Client does not support authentication protocol requested by server; consider upgrading MySQL client`

**Comment by Romfos** [comment]
@billy1arm

PR for mysql 8:
 https://github.com/mangosvb/DatabaseZero/pull/2

**Comment by Meltie2013** [comment]
@Romfos 
Should support MariaDB 10 as well, just so others that have it don't have to download another to run the project.

**Comment by Romfos** [comment]
@Meltie2013 could you please check with https://github.com/mangosvb/DatabaseZero/pull/2 on MariaDB 10?

**Comment by Meltie2013** [comment]
@Romfos Sure I can give it a check.

**Comment by billy1arm** [comment]
@Romfos  - This line seems to indicate that the server will use mysql 8 by default which is incorrect:
https://github.com/mangosvb/serverZero/pull/132/files#diff-58dccd3b4fd522c37a74bf96f868e293R26

We have had quite a lot of trouble with mysql 8.0 over on the c++ mangos repos which is still ongoing.
- 8.0 breaks a lot of things, apart from the obvious permission stuff.

The entire codebase needs to be checked and fixed before we ever attempt to upgrade support to include 8.0.
- for now 8.0 MUST BE INSTALLED with legacy permissions included just to get it to run.

If you use skype or discord at all, let me know and we can discuss it in more detail.

**Comment by Romfos** [comment]
@billy1arm 
No, this line https://github.com/mangosvb/serverZero/pull/132/files#diff-58dccd3b4fd522c37a74bf96f868e293R26 contains version for mysql nuget package version (mysql client for .net). 
It is comatiable with mysql 5.6 (that i'm using), not only 8.0

More info:
https://dev.mysql.com/doc/connector-net/en/connector-net-versions.html
`MySQL Connector/NET 8.0 is highly recommended for use with MySQL Server 8.0, 5.7, and 5.6. Please upgrade to MySQL Connector/NET 8.0.`

I have discord and I'm joined to 'getMaNGOS Devloper' group. You can find me there:)

**Comment by Romfos** [comment]
@billy1arm @Meltie2013 any updates 😄 ?

**Comment by billy1arm** [comment]
Thank you for your contribution

**Pull request merged**
